[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

build_flags =
    -std=gnu++14
    -Os
    -Wall
    -Wextra
    -I include
    -I src/modules/display
    -I src/modules/env_sensor
    -I src/modules/fan_controller
    -I src/modules/network
    -I src/modules/mqtt_client

monitor_speed = 115200

upload_speed = 921600
board_build.flash_mode = dio
board_build.f_cpu = 240000000L

lib_deps =
    adafruit/Adafruit AHTX0 @ ^2.0.5
    adafruit/Adafruit BusIO @ ^1.16.1
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
